##spring:
##  #通用数据配置
##  datasource:
##    url: jdbc:mysql://localhost:3306/marksystem?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowMultiQueries=true
##    username: root
##    password: root
##    driver-class-name: com.mysql.cj.jdbc.Driver
##   #JPA 配置
##  jpa:
##    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
##    show-sql: true
##    hibernate:
##      ddl-auto: update
#
#spring:
#  redis:
#    cluster:
#      ports:
#        - 7000
#        - 7001
#        - 7002
#        - 7003
#        - 7004
#        - 7005
#      host: 192.168.186.129
#      poolConfig:
#        max-total: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait-millis: -1
#
#
#

spring:
  redis:
    database: 0
    #    host: 192.168.1.48
    #    port: 6379
    #    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
    cluster:
      logs: true
      nodes:
      - 192.168.186.129:7000
      - 192.168.186.129:7001
      - 192.168.186.129:7002
      - 192.168.186.129:7003
      - 192.168.186.129:7004
      - 192.168.186.129:7005
      max-redirects: